BOARD_NAME               := lichee_th1520_fullflash
BOARD_HEADER             := boards/lichee_th1520_fullflash.h
DDR_ADDR                 := 0x40000000
YOUR_RAW_BIN             := image_simon_lichee.bin
MAX_RAW_IMAGE_SIZE       := 0x800000
FULLFLASH_BIN            := flash_me_lichee.bin
WRAPPED_BIN              := simon_wrapped_lichee.img
UBOOT_SPL_BIN            ?= firmware/u-boot-with-spl.bin
UBOOT_IMAGE_NAME         := SimonOS-Lichee
FULLFLASH_SIZE           := 0x800000
FULLFLASH_PAYLOAD_OFFSET := 0x100000
FULLFLASH_READ_ADDR      := 0x30000000
UBOOT_RAW_COMMAND        := load mmc 1:2 $(DDR_ADDR) /$(YOUR_RAW_BIN); go $(DDR_ADDR)
SUPPORTS_FULLFLASH       := 1
